---
abstract: 'Authenticate with Google'
author:
  - 'Breno G. de Oliveira <garu@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.02, CPAN::Meta::Converter version 2.142690'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Dancer-Plugin-Auth-Google
no_index:
  directory:
    - t
    - inc
requires:
  Carp: '0'
  Dancer: '0'
  Furl: '0'
  IO::Socket::SSL: '0'
  Test::More: '0'
  Try::Tiny: '0'
  URI: '0'
resources:
  repository: http://github.com/garu/Dancer-Plugin-Auth-Google
version: 0.05
